name: Cloud2 Trivy IaC Scan
description: Scans IaC files using Trivy

on:
  workflow_call:
    inputs:
      advanced-security-enabled:
        type: boolean
        required: false
        default: false

      severity:
        type: string
        required: false
        default: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL' # All findings

      hard-fail:
        type: boolean
        required: false
        default: false

jobs:
  build:
    name: Trivy IaC Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@a11da62073708815958ea6d84f5650c78a3ef85b # 8.1.2025 commit
        with:
          scan-type: 'config'
          limit-severities-for-sarif: ${{ inputs.advanced-security-enabled }}
          format: ${{ inputs.advanced-security-enabled && 'sarif' || 'table' }}
          output: ${{ inputs.advanced-security-enabled && 'trivy-results.sarif' || '' }}
          severity: ${{ inputs.severity }}
          exit-code: ${{ inputs.hard-fail && 1 || 0 }}

      - name: Upload SARIF
        if: ${{ inputs.advanced-security-enabled }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'